name: Build CUDA Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up MSBuild
      run: |
        start /wait "" ".\testing\vs_BuildTools.exe" /quiet /norestart

    - name: Confirm MSBuild Version
      run: |
        msbuild --version

    - name: Set up CUDA
      uses: Jimver/cuda-toolkit@v0.2.17
      with:
        cuda: '12.1.0'
        method: 'local'
        sub-packages: '["nvcc", "cudart", "cublas", "cublas_dev", "thrust", "visual_studio_integration"]'

    - name: Build the project
      run: |
        msbuild BrendanCUDA.sln /p:Configuration=Release
